package ba.sake.deder.buildinfo

import ba.sake.deder.{*, given}
import ba.sake.deder.config.DederProject.{DederModule, JavaModule, JavaTestModule, ScalaModule, ScalaTestModule}
import ba.sake.deder.config.DederProject.ModuleType
import ba.sake.deder.BuildInfo

object BuildInfoGenerationTasks {

  private def moduleRoot(module: DederModule): os.Path =
    if module.root == "." then DederGlobals.projectRootDir
    else DederGlobals.projectRootDir / os.RelPath(module.root)

  private val supportedModuleTypes: Set[ModuleType] =
    Set(ModuleType.JAVA, ModuleType.JAVA_TEST, ModuleType.SCALA, ModuleType.SCALA_TEST)

  def sourceGeneratorTask(
      config: BuildInfo.BuildInfoPluginConfig
  ): AbstractTask[os.Path] =
    TaskBuilder
      .make[os.Path](
        name = "buildInfoGenerate",
        supportedModuleTypes = supportedModuleTypes,
        category = "BuildInfo",
        kind = TaskKind.SourceGenerator
      )
      .build { ctx =>
        val moduleName = ctx.module.id
        val (moduleType, scalaVersion) = extractModuleMeta(ctx.module)
        val resolved = BuildInfoConfigNormalizer.normalize(
          moduleId = moduleName,
          moduleType = moduleType,
          scalaVersion = scalaVersion,
          config = config
        )
        val sourceOut = ctx.out / "sources"
        prepareDirectory(sourceOut)

        if !resolved.enabled then sourceOut
        else {
          val gitHash = if resolved.includeGitHash then {
            val root = moduleRoot(ctx.module)
            Some(GitSupport.gitHead(root))
          } else None

          val timestamp = if resolved.includeTimestamp then Some(System.currentTimeMillis()) else None

          val sourceCode = generateScalaSource(
            moduleName = moduleName,
            config = resolved,
            gitHash = gitHash,
            timestamp = timestamp
          )

          val pkgPath = resolved.packageName match {
            case Some(pkg) => os.RelPath(pkg.replace('.', '/'))
            case None => os.RelPath(".")
          }
          val pkgDir = sourceOut / pkgPath
          os.makeDir.all(pkgDir)
          val sourceFile = pkgDir / s"${resolved.objectName}.scala"
          os.write(sourceFile, sourceCode)
          sourceOut
        }
      }

  private[buildinfo] def generateScalaSource(
      moduleName: String,
      config: ResolvedBuildInfoConfig,
      gitHash: Option[String] = None,
      timestamp: Option[Long] = None
  ): String = {
    val pkgDecl = config.packageName.map(pkg => s"package $pkg\n\n").getOrElse("")
    val header = "// Generated by deder-build-info. DO NOT EDIT.\n\n"

    val vals = collection.mutable.ListBuffer.empty[String]
    val toMapEntries = collection.mutable.ListBuffer.empty[String]

    def addVal(name: String, tpe: String, value: String): Unit = {
      vals += s"  val $name: $tpe = $value"
      toMapEntries += s""""$name" -> $name"""
    }

    addVal("moduleName", "String", s"\"$moduleName\"")
    addVal("moduleVersion", "String", "\"0.1.0-SNAPSHOT\"")
    config.scalaVersion.foreach(v => addVal("scalaVersion", "String", s"\"$v\""))
    addVal("javaVersion", "String", s"\"${System.getProperty("java.version")}\"")
    gitHash.foreach(h => addVal("gitHead", "String", s"\"$h\""))
    timestamp.foreach(t => addVal("builtAtMillis", "Long", s"${t}L"))

    config.extra.toSeq.sortBy(_._1).foreach { case (key, value) =>
      val escapedValue = value.replace("\\", "\\\\").replace("\"", "\\\"")
      addVal(key, "String", s"\"$escapedValue\"")
    }

    val toMapBody = toMapEntries.mkString(",\n      ")

    s"""$header${pkgDecl}object ${config.objectName} {
       |${vals.mkString("\n\n")}
       |
       |  def toMap: Map[String, Any] = Map(
       |      $toMapBody
       |    )
       |}
       |""".stripMargin
  }

  private def extractModuleMeta(module: DederModule): (String, Option[String]) =
    module match {
      case m: ScalaTestModule => ("SCALA", trimToOption(m.scalaVersion))
      case _: JavaTestModule => ("JAVA", None)
      case m: ScalaModule => ("SCALA", trimToOption(m.scalaVersion))
      case _: JavaModule => ("JAVA", None)
      case other => throw IllegalArgumentException(s"Unsupported module type: ${other.getClass.getName}")
    }

  private def trimToOption(value: String): Option[String] =
    Option(value).map(_.trim).filter(_.nonEmpty)

  private def prepareDirectory(path: os.Path): Unit = {
    if os.exists(path) then os.remove.all(path)
    os.makeDir.all(path)
  }
}
