#Java mappings for Pkl module `ba.sake.deder.plugins.openapi4s`
#Fri Sep 25 19:53:06 CEST 2026
org.pkl.config.java.mapper.ba.sake.deder.plugins.openapi4s\#ModuleClass=ba.sake.deder.plugins.Openapi4s
org.pkl.config.java.mapper.ba.sake.deder.plugins.openapi4s\#ModuleDefaults=ba.sake.deder.plugins.Openapi4s$ModuleDefaults
org.pkl.config.java.mapper.ba.sake.deder.plugins.openapi4s\#ModuleOverride=ba.sake.deder.plugins.Openapi4s$ModuleOverride
org.pkl.config.java.mapper.ba.sake.deder.plugins.openapi4s\#Openapi4sPlugin=ba.sake.deder.plugins.Openapi4s$Openapi4sPlugin
org.pkl.config.java.mapper.ba.sake.deder.plugins.openapi4s\#Openapi4sPluginConfig=ba.sake.deder.plugins.Openapi4s$Openapi4sPluginConfig
