#Java mappings for Pkl module `ba.sake.deder.plugins.buildinfo`
#Wed Jun 10 17:26:01 CEST 2026
org.pkl.config.java.mapper.ba.sake.deder.plugins.buildinfo\#BuildInfoPlugin=ba.sake.deder.plugins.Buildinfo$BuildInfoPlugin
org.pkl.config.java.mapper.ba.sake.deder.plugins.buildinfo\#BuildInfoPluginConfig=ba.sake.deder.plugins.Buildinfo$BuildInfoPluginConfig
org.pkl.config.java.mapper.ba.sake.deder.plugins.buildinfo\#ModuleClass=ba.sake.deder.plugins.Buildinfo
org.pkl.config.java.mapper.ba.sake.deder.plugins.buildinfo\#ModuleDefaults=ba.sake.deder.plugins.Buildinfo$ModuleDefaults
org.pkl.config.java.mapper.ba.sake.deder.plugins.buildinfo\#ModuleOverride=ba.sake.deder.plugins.Buildinfo$ModuleOverride
