#Java mappings for Pkl module `ba.sake.deder.plugins.sourcegen`
#Wed Jun 24 14:47:00 CEST 2026
org.pkl.config.java.mapper.ba.sake.deder.plugins.sourcegen\#ModuleClass=ba.sake.deder.plugins.Sourcegen
org.pkl.config.java.mapper.ba.sake.deder.plugins.sourcegen\#ModuleDefaults=ba.sake.deder.plugins.Sourcegen$ModuleDefaults
org.pkl.config.java.mapper.ba.sake.deder.plugins.sourcegen\#ModuleOverride=ba.sake.deder.plugins.Sourcegen$ModuleOverride
org.pkl.config.java.mapper.ba.sake.deder.plugins.sourcegen\#SourcegenPlugin=ba.sake.deder.plugins.Sourcegen$SourcegenPlugin
org.pkl.config.java.mapper.ba.sake.deder.plugins.sourcegen\#SourcegenPluginConfig=ba.sake.deder.plugins.Sourcegen$SourcegenPluginConfig
