#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PKL_FILE="$ROOT_DIR/resources/WebDashboardPlugin.pkl"
WORK_DIR="$ROOT_DIR/tmp/.gen-plugin-bindings.$BASHPID"
JAVA_GENERATED_MARKER="DO NOT EDIT: your changes will be overwritten."
RESOURCE_GENERATED_MARKER="Generated by ./scripts/gen-plugin-bindings.sh; do not edit by hand."

cleanup() {
  rm -rf "$WORK_DIR"
}
trap cleanup EXIT

remove_generated_files() {
  local target_dir="$1"
  local file_glob="$2"
  local marker="$3"

  if [[ ! -d "$target_dir" ]]; then
    return
  fi

  python - "$target_dir" "$file_glob" "$marker" <<'PY'
from pathlib import Path
import sys

target_dir = Path(sys.argv[1])
file_glob = sys.argv[2]
marker = sys.argv[3]

for path in target_dir.rglob(file_glob):
    if not path.is_file():
        continue

    try:
        contents = path.read_text()
    except UnicodeDecodeError:
        continue

    if marker in contents:
        path.unlink()

for path in sorted(target_dir.rglob("*"), key=lambda item: len(item.parts), reverse=True):
    if path.is_dir():
        try:
            path.rmdir()
        except OSError:
            pass
PY
}

add_generated_warning() {
  local java_dir="$1"

  if [[ ! -d "$java_dir" ]]; then
    return
  fi

  python - "$java_dir" <<'PY'
from pathlib import Path
import sys

java_dir = Path(sys.argv[1])
header = """/*
 * This file is generated by ./scripts/gen-plugin-bindings.sh from resources/WebDashboardPlugin.pkl.
 * DO NOT EDIT: your changes will be overwritten.
 */

"""

for java_file in java_dir.rglob("*.java"):
    contents = java_file.read_text()
    if "DO NOT EDIT" not in contents:
        java_file.write_text(header + contents)
PY
}

normalize_generated_resources() {
  local resources_dir="$1"

  if [[ ! -d "$resources_dir" ]]; then
    return
  fi

  python - "$resources_dir" <<'PY'
from pathlib import Path
import sys

resources_dir = Path(sys.argv[1])
properties_file = resources_dir / "META-INF" / "org" / "pkl" / "config" / "java" / "mapper" / "classes" / "ba.sake.deder.webdashboard.properties"

if properties_file.exists():
    lines = properties_file.read_text().splitlines()
    if len(lines) >= 2 and lines[0].startswith("#Java mappings for Pkl module"):
        lines[1] = "# Generated by ./scripts/gen-plugin-bindings.sh; do not edit by hand."
        properties_file.write_text("\n".join(lines) + "\n")
else:
    print(
        f"warning: expected generated mapper properties at {properties_file} but pkl-codegen-java did not produce it",
        file=sys.stderr,
    )
PY
}

if ! command -v pkl-codegen-java >/dev/null 2>&1; then
  echo "pkl-codegen-java is required on PATH" >&2
  exit 1
fi

echo "Generating Java bindings from $PKL_FILE"
mkdir -p "$WORK_DIR"
pkl-codegen-java "$PKL_FILE" -o "$WORK_DIR"
add_generated_warning "$WORK_DIR/java"
normalize_generated_resources "$WORK_DIR/resources"
remove_generated_files "$ROOT_DIR/src" "*.java" "$JAVA_GENERATED_MARKER"
remove_generated_files "$ROOT_DIR/resources" "*" "$RESOURCE_GENERATED_MARKER"
cp -r "$WORK_DIR/java/." "$ROOT_DIR/src"
cp -r "$WORK_DIR/resources/." "$ROOT_DIR/resources"
echo "Bindings updated under src and resources"
